name: Host Service CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.js"]

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout
      uses: actions/checkout@v3

    - name: 2. Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secret.DOCKER_USERNAME }}
        password: ${{ secret.DOCKER_PASSWORD }}

    - name: 3. Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: dangtong/hostservice:${{ github.sha }}

