name: Host Service CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.js"]

jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout
      uses: actions/checkout@v3

    - name: 2. Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 3. Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ty990520/hostservice:${{ github.sha }}

  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - name: 1. Checkout
        uses: actions/checkout@v3
        with: 
          repository: 'ty990520/hostsvc-cd'
          token: ${{ secrets.HUB_TOKEN }}

      - name: 2. Change Docker Tag
        run: |
          sed -i "s/image: ty990520\/node-app:.*/images: ty990520\/node-app:${{ github.sha }}/g" hostservice-deploy.yaml  
          git config --global user.email "ty990520@naver.com"
          git config --global user.name "ty990520"
          git commit -am "triggered by github action"
          git push origin main
